import logging
import time

from discord_webhook import DiscordEmbed, DiscordWebhook

from src.models import DigestOutput, Settings

logger = logging.getLogger(__name__)


def deliver(digest: DigestOutput, settings: Settings) -> None:
    webhook = DiscordWebhook(
        url=settings.discord_webhook_url,
        username="AI Morning Brief",
    )

    for i, chunk in enumerate(digest.chunks):
        color = "1a73e8" if i == 0 else "6c757d"
        embed = DiscordEmbed(
            title=digest.title if i == 0 else f"{digest.title} (cont.)",
            description=chunk,
            color=color,
        )
        if i == len(digest.chunks) - 1:
            embed.set_footer(text="Generated by AI Morning Brief")
            embed.set_timestamp()
        webhook.add_embed(embed)

        # Discord allows max 10 embeds per message
        if (i + 1) % 10 == 0:
            _execute_with_retry(webhook)
            webhook = DiscordWebhook(
                url=settings.discord_webhook_url,
                username="AI Morning Brief",
            )

    if webhook.embeds:
        _execute_with_retry(webhook)

    logger.info("Digest delivered to Discord")


def _execute_with_retry(
    webhook: DiscordWebhook, max_retries: int = 3
) -> None:
    for attempt in range(max_retries):
        response = webhook.execute()
        if response and response.status_code in (200, 204):
            return
        if response and response.status_code == 429:
            retry_after = response.json().get("retry_after", 5)
            logger.warning(f"Rate limited, retrying after {retry_after}s")
            time.sleep(retry_after)
        else:
            time.sleep(2**attempt)
    raise RuntimeError(
        f"Discord webhook failed after {max_retries} retries"
    )
