import logging
import time

from discord_webhook import DiscordEmbed, DiscordWebhook

from src.models import DigestOutput, Settings

logger = logging.getLogger(__name__)

# Discord limit: total chars across all embeds in one message must be ≤ 6000.
# Since chunks can be up to 4096 chars, we send one embed per message to stay safe.


def deliver(digest: DigestOutput, settings: Settings) -> None:
    for i, chunk in enumerate(digest.chunks):
        webhook = DiscordWebhook(
            url=settings.discord_webhook_url,
            username="AI Morning Brief",
        )

        color = "1a73e8" if i == 0 else "6c757d"
        embed = DiscordEmbed(
            title=digest.title if i == 0 else f"{digest.title} (cont.)",
            description=chunk,
            color=color,
        )
        if i == len(digest.chunks) - 1:
            embed.set_footer(text="Generated by AI Morning Brief")
            embed.set_timestamp()
        webhook.add_embed(embed)
        _execute_with_retry(webhook)

    logger.info(f"Digest delivered to Discord ({len(digest.chunks)} message(s))")


def _execute_with_retry(
    webhook: DiscordWebhook, max_retries: int = 3
) -> None:
    for attempt in range(max_retries):
        response = webhook.execute()
        if response and response.status_code in (200, 204):
            return
        if response and response.status_code == 429:
            retry_after = response.json().get("retry_after", 5)
            logger.warning(f"Rate limited, retrying after {retry_after}s")
            time.sleep(retry_after)
        else:
            time.sleep(2**attempt)
    raise RuntimeError(
        f"Discord webhook failed after {max_retries} retries"
    )
